# Time
TIME_FRAME_IN_YEARS = 50

# Cash
INITIAL_CASH = 50000
SALARY = 2500
SALARY_INCREASE = 0.05

# Financing
LOAN_INTEREST_RATE = 0.036
INITIAL_LOAN_AMORTIZATION_RATE = 0.01

# Stocks
AVERAGE_STOCK_RETURN = 0.1

# Property
# Price and rent for Eschborn, taken from the internet
PROPERTY_AREA = 100
RENT_PER_SQUARE_METER = 14.49
PRICE_PER_SQUARE_METER = 4130
PROPERTY_VALUE_INCREASE_PER_YEAR = 0.05
YEARLY_PROPERTY_MAINTENANCE_COSTS = 0.014
PROPERTY_PURCHASE_TAX_RATE = 0.06
PROPERTY_PURCHASE_NOTARY_COST_RATE = 0.015
PROPERTY_PURCHASE_BROKERAGE = 0.0357
